### ISSUE TITLE
postgrest on heroku -- issue with crossdomain requests

### ISSUE THREAD

**Issue by mikesmayer** [PostgREST/postgrest-heroku#12]
I am able to run a postgrest server locally. Both the js front end app and the rails app seems to run fine on my local machine, but I'm running into an error when I try to run it on heroku.

I can't seem to get the API to run properly while running the server on Heroku

This is the error I'm receiving:

XMLHttpRequest cannot load https://api.citizensupported.org/user_details?id=eq.2. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.citizensupported.org' is therefore not allowed access. The response had HTTP status code 503.

I'm using the button at https://elements.heroku.com/buttons/begriffs/postgrest to deploy the postgrest server -- I think this recently got upgraded to v0.4.0.0

Any advice?

I'm not sure if I'm following the right approach to running a postgrest server on heroku.

**Comment by begriffs** [comment]
My apologies, the 0.4 version doesn't work with the old heroku buildpack. That's because the buildpack starts the postgrest executable with command line arguments but the new version is expecting a single argument for the config file.

We need to modify the buildpack to create a config file during deployment -- but to do so conditionally if version 0.4 is desired.

**Comment by mikesmayer** [comment]
gosh, you're a superstar. thanks for responding so quickly.

what's the right way to work around this until you update the build pack?

**Comment by LutherDiaz** [comment]
@begriffs what else is missing in the fix-0.4 branch?

**Comment by abernicchia-heroku** [comment]
the button https://elements.heroku.com/buttons/begriffs/postgrest is not present anymore, is this issue still relevant?
