### ISSUE TITLE
Possibly deprecate in favor of container registry

### ISSUE THREAD

**Issue by begriffs** [PostgREST/postgrest-heroku#15]
Heroku is testing the deployment of apps via Dockerfiles. When this comes out of beta perhaps we can re-use the postgrest Docker image and drop support for this old-fashioned buildpack.

https://devcenter.heroku.com/articles/container-registry-and-runtime

**Comment by aliw77** [comment]
any progress on this? if not can you suggest what is the best way to update an existing app to latest binaries?

**Comment by begriffs** [comment]
I haven't experimented with Docker on Heroku. However if you want to upgrade the PostgREST version of your app you should be able to bump the `POSTGREST_VER` to a later version and redeploy the app by pushing another git commit to the heroku endpoint. Also you'll want to fill in the variables found [here](https://github.com/begriffs/postgrest/blob/master/app.json) since some of the variable names have changed since earlier versions.

**Comment by christiaanwesterbeek** [comment]
The buildpack deploys delightfully simple. I love it. Not sure if I can say the same about docker images.

**Comment by abernicchia-heroku** [comment]
hugely simplified with this PR https://github.com/PostgREST/postgrest-heroku/pull/40 - still in favour of buildpacks in my book
