### ISSUE TITLE
Heroku Postgres Addon Fix ?

### ISSUE THREAD

**Issue by mgcdanny** [PostgREST/postgrest-heroku#16]
Hi,

Not sure if anyone is trying to scratch this itch but I came across a new Heroku feature that might allow compatibility with the heroku Postgres Addon... 

https://devcenter.heroku.com/articles/heroku-postgresql-credentials

**Comment by cpursley** [comment]
Has anyone had success using this approach with Heroku Postgres with PostgREST?

**Comment by steve-chavez** [comment]
Also requested in https://github.com/PostgREST/postgrest/issues/1050, let's continue the discussion there.

**Comment by steve-chavez** [comment]
Actually the issue will be better on this repo. Reopening..

**Comment by abernicchia-heroku** [comment]
it can be fixed with this PR https://github.com/PostgREST/postgrest-heroku/pull/40 as described in the README.md
