### ISSUE TITLE
Is the buildpack really using 0.4.4.0?

### ISSUE THREAD

**Issue by christiaanwesterbeek** [PostgREST/postgrest-heroku#17]
Are you sure the thing at this location is really a 0.4.4.0 version?

http://bin.begriffs.com/dbapi/heroku/postgrest-0.4.4.0.tar.xz

Using the buildpack on Heroku and a deploy with POSTGREST_VER=0.4.4.0:
![image](https://user-images.githubusercontent.com/465989/38698953-02bfe1ce-3e97-11e8-8592-b519dd0139b9.png)

The Postgrest server always returns a response header: `Server: postgrest/0.4.0.0`

![image](https://user-images.githubusercontent.com/465989/38698704-41c4744e-3e96-11e8-828c-fb7aeb87bcdf.png)

**Comment by begriffs** [comment]
Hm, looks like it's falling back to the default version, as if `POSTGREST_VER` was undefined. https://github.com/begriffs/postgrest-heroku/blob/master/bin/compile#L13

I'm not willing to [spend time](https://begriffs.com/posts/2018-04-02-no-more-freebies.html) debugging this for free, but would accept a pull request.

**Comment by christiaanwesterbeek** [comment]
Yes. I'm starting to suspect that it's getting the one from the cache. When I deployed the app for the first time. The POSTGREST_VER config wasn't there yet.

This is my deploy log now:

```
-----> DBAPI app detected
-----> Exporting config vars
       DB_ANON_ROLE
       DB_POOL
       DB_SCHEMA
       DB_URI
       JWT_SECRET
       POSTGREST_VER
-----> Restoring cached libraries
-----> Restoring cached postgrest
-----> Copying the config file builder
-----> Creating Procfile
-----> Persisting settings
-----> ❤ stay declarative ❤
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
       Done: 7.8M
-----> Launching...
       Released v13
       https://xxx.herokuapp.com/ deployed to Heroku
```

It's missing the line that says `-----> Downloading and caching libraries for POSTGREST` as per https://github.com/begriffs/postgrest-heroku/blob/master/bin/compile#L51

I'm trying to find out right now how to clear the library cache for an Heroku app...

I will post an update once I find out

**Comment by christiaanwesterbeek** [comment]
> I'm not willing to spend time debugging this for free

That's OK. I totally understand. I read your post about it. Smart move!

**Comment by christiaanwesterbeek** [comment]
Yep, it was cache. And here's the solution: https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache

```
$ heroku plugins:install heroku-repo
$ heroku repo:purge_cache -a appname
$ git commit --allow-empty -m "Purge cache"
$ git push heroku master
```

Now this is my deploy log:

```
-----> DBAPI app detected
-----> Exporting config vars
       DB_ANON_ROLE
       DB_POOL
       DB_SCHEMA
       DB_URI
       JWT_SECRET
       POSTGREST_VER
-----> Downloading and caching libraries for POSTGREST
-----> Downloading and caching POSTGREST 0.4.4.0 binary
-----> Restoring cached postgrest
-----> Copying the config file builder
-----> Creating Procfile
-----> Persisting settings
-----> ❤ stay declarative ❤
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
       Done: 10M
-----> Launching...
       Released v14
       https://xxx.herokuapp.com/ deployed to Heroku
```

With the important difference: `-----> Downloading and caching POSTGREST 0.4.4.0 binary`

Server now response with header: `Server: postgrest/0.4.4.0 (f9e770b)`

Fixed.

**Comment by christiaanwesterbeek** [comment]
PR: https://github.com/begriffs/postgrest-heroku/pull/18
