### ISSUE TITLE
Publish buildpack for 0.5.0.0

### ISSUE THREAD

**Issue by christiaanwesterbeek** [PostgREST/postgrest-heroku#19]
I suppose what's needed is a `http://bin.begriffs.com/dbapi/heroku/postgrest-0.5.0.0.tar.xz` or `http://bin.begriffs.com/dbapi/heroku/postgrest-v0.5.0.0.tar.xz` file available and optionally update the default to 0.5.0.0 in https://github.com/PostgREST/postgrest-heroku/blob/master/bin/compile#L13

**Comment by steve-chavez** [comment]
Had this on my to-do list, as I don't control that domain I'm gonna have to host the binaries somewhere else, was thinking of adding the new version binary to a github release in this project, do you foresee any problems with that?

**Comment by christiaanwesterbeek** [comment]
I don't foresee any problems. I would commit a `/bin/buildpack.tar.xz` and release v0.5.0.0. The file would  become downloadable by: `https://github.com/PostgREST/postgrest-heroku/raw/v0.5.0.0/bin/buildpack.tar.xz`

Then change the 2 lines in bin/compile that now link to bin.begriffs.com. Also change the readme.md file. And somehow update what is shown here to reflect the change: https://elements.heroku.com/buildpacks/postgrest/postgrest-heroku

**Comment by christiaanwesterbeek** [comment]
Thanks! https://elements.heroku.com/buildpacks/postgrest/postgrest-heroku still shows an outdated version of README.md. Not sure if it pulls from master at some interval or you need to do something to get it to update.

**Comment by steve-chavez** [comment]
`0.5.0.0` Seems to be working fine now. Haven't found a way to manually update the elements.heroku.com page, maybe it self-updates according to the github repo, let's give it a while to see if it happens.

**Comment by steve-chavez** [comment]
The https://elements.heroku.com/buildpacks/postgrest/postgrest-heroku page is now showing the updated README.
