### ISSUE TITLE
Add role-claim-key to variables

### ISSUE THREAD

**Issue by tayupov** [PostgREST/postgrest-heroku#21]
`env-to-config` file is missing `role-claim-key` as available variable.
See: https://github.com/PostgREST/postgrest/pull/1091

**Comment by steve-chavez** [comment]
I'd really appreciate a PR on this, see if you can add the variable and test it works on Heroku.

**Comment by tayupov** [comment]
I got it to run by adding it manually and using a fork as buildpack as you can see here:
https://github.com/tayupov/postgrest-heroku/blob/master/env-to-config

However, it will not work with "Heroku Postgres", but works with AWS RDS.

**Comment by steve-chavez** [comment]
Heroku postgres handles pg roles in a special way and we recommend RDS, so I think that's ok.
