### ISSUE TITLE
Build fails on Heroku

### ISSUE THREAD

**Issue by lee-40square** [PostgREST/postgrest-heroku#23]
I followed the directions and got the following error:

```
-----> PostgREST app detected
-----> Exporting config vars
       DB_ANON_ROLE
       DB_SCHEMA
       DB_URI
       POSTGREST_VER
-----> Downloading and caching libraries for PostgREST
#=#=#                                 -----> Could not find prebuilt postgrest
 !     Push rejected, failed to compile PostgREST app.
 !     Push failed

```

**Comment by steve-chavez** [comment]
I've tried with the Heroku Deploy Button and it's working good for me, make sure to set the `POSTGREST_VER` to `5.1.0`.

**Comment by lee-40square** [comment]
I didn't realize that there was a Deploy Button. I may have missed that in the documentation somewhere. That worked for me. Thanks.
