### ISSUE TITLE
How to specify the role claim key

### ISSUE THREAD

**Issue by Fohlen** [PostgREST/postgrest-heroku#25]
Some keys may use `"` (e.g `."https://somedomain/key"`)  and will break the deployment. With the `JWT_SECRET` we can specify a base64 encoded string, but this is not possible with the `ROLE_CLAIM_KEY`

**Comment by steve-chavez** [comment]
It's possible to have a json key with a domain name in `role-claim-key`, you'll have to escape the quotes `"`.

There's an example here: http://postgrest.org/en/v6.0/configuration.html#role-claim-key.

**Comment by Fohlen** [comment]
@steve-chavez I am aware that I can do this, however it will break the `env-to-config` script by producing a config with invalid line endings

**Comment by steve-chavez** [comment]
Hmm, could that be fixed in these lines?

https://github.com/PostgREST/postgrest-heroku/blob/c4ed3779c25ff1335f2636294d953deb1d7d6e2c/env-to-config#L21-L32

I'd appreciate your help with this, it's been a while since I've touched postgrest-heroku.

**Comment by Fohlen** [comment]
@steve-chavez I specifically think this:
```
".\"https://somedomain.example/key\""
```
breaks in line 27

**Comment by Fohlen** [comment]
I solved my issues by modifying `env-to-config` manually as in https://github.com/PostgREST/postgrest-heroku/compare/master...eventzimmer:master

However this is bad practice and I do not know how to fix it. It's just a hint for anyone stuck with a similar problem.

**Comment by Fohlen** [comment]
Notably when trying to use the `JWT_SECRET` and `ROLE_CLAIM_KEY` with quoted strings, it will produce an invalid config like mentioned here: https://github.com/PostgREST/postgrest/issues/937

**Comment by abernicchia-heroku** [comment]
this should be fixed with this PR https://github.com/PostgREST/postgrest-heroku/pull/40 as it removes the use of the env-to-config scripts in favour of env vars
