### ISSUE TITLE
Add JWT_AUD value

### ISSUE THREAD

**Issue by Fohlen** [PostgREST/postgrest-heroku#26]
Currently the `JWT_AUD` is not set during deployment. This is necessary when deploying from Auth0

**Comment by steve-chavez** [comment]
What would be a good default for `JWT_AUD`?

**Comment by Fohlen** [comment]
That is indeed a good question. Can the script be modified, so by default it is empty?

**Comment by steve-chavez** [comment]
It's not empty by default?(I thought the [app.json](https://github.com/PostgREST/postgrest/blob/master/app.json#L46-L49) made it empty).

But sure, you can modify the script and do a PR if you'd like.
