### ISSUE TITLE
Heroku image hangs on request

### ISSUE THREAD

**Issue by parauchf** [PostgREST/postgrest-heroku#3]
Hi, sorry to bother, I've been trying to get this image to work for most of today and at my wits end.

So far I have:
- set up an amazon postgres RDS and can log in using psql
- created a new role and two user accounts
- created the "1" schema and some test views
- created a heroku image based on this buildpack
- updated the config vars to match my database 

When I launch any request to the postgrest server it just hangs and then times out.  I have noticed that it crashes on startup if the db configs are incorrect, so I'm pretty sure something is working.  The logs are not helpful and I don't know any haskell, so I thought I'd reach out for a clue?

**Comment by begriffs** [comment]
What do the heroku logs say? Also which version of postgrest are you running?

**Comment by parauchf** [comment]
Thanks @begriffs for responding!  This looks like a very cool project BTW.

I just used the latest master so looks like I'm using 0.2.10.0  Here's a snippet from the heroku logs:

Jun 09 19:18:19 pgrtest heroku/web.1:  Stopping all processes with SIGTERM 
Jun 09 19:18:20 pgrtest heroku/web.1:  Starting process with command `./postgrest-0.2.10.0 -p 6620 -s -d pgrtest -U pgradmin --db-pass XXXXXX -a pgrsvc --db-host pgrtest.XXXXXXXX.us-east-1.rds.amazonaws.com -P 5432 --db-pool 10` 
Jun 09 19:18:21 pgrtest heroku/web.1:  Process exited with status 143 
Jun 09 19:18:23 pgrtest heroku/web.1:  State changed from starting to up 
Jun 09 19:19:05 pgrtest heroku/router:  at=error code=H12 desc="Request timeout" method=GET path="/" host=pgrtest.herokuapp.com request_id=3f325c0b-5eea-4a34-9398-b3925a10765e fwd="96.224.200.76" dyno=web.1 connect=0ms service=30001ms status=503 bytes=0 

And here's the working psql command:

psql -h "pgrtest.XXXXXX.us-east-1.rds.amazonaws.com" -p 5432 -U pgrsvc -d pgrtest

**Comment by parauchf** [comment]
Figured it out. Sorry to drag you into this!

By default, RDS sets up a firewall based on your current IP range so I could access the instance from my laptop, but heroku instance could not.  

It would be good to return an error message if the database is unreachable.

**Comment by parauchf** [comment]
So possible solutions I can think of:
1. Open the firewall to allow all inbound traffic (probably fine for dev)
2. Use an outbound http proxy (e.g., Heroku's Proximo)

**Comment by begriffs** [comment]
Nice debugging!

Would you mind editing this wiki page to share your findings? https://github.com/begriffs/postgrest/wiki/Heroku

It could help other people who might encounter these problems.

**Comment by parauchf** [comment]
Absolutely.

**Comment by begriffs** [comment]
Your docs are fantastic, thank you very much!

I'll link to them on the postgrest readme.
