### ISSUE TITLE
Function in public schema cannot be found

### ISSUE THREAD

**Issue by Vizz85** [PostgREST/postgrest-heroku#32]
I'm using PostgREST-Heroku to make API calls to a database on Heroku which uses Heroku-Connect to sync data to a Salesforce database (not sure if this is relevant).

The problem is that the schema against which I consume the API (named "salesforce") is using a function stored in the public schema (function is named "get_xmlbinary") and I'm receiving this error when trying to POST or PATCH rows
`{`
    `  "hint": "No function matches the given name and argument types. You might need to add explicit type casts.",`
    `  "details": null,`
    `  "code": "42883",`
    `  "message": "function get_xmlbinary() does not exist"`
`}`

Calling the function with POST /rpc/get_xmlbinary produces a slightly different message:
`"message": "function salesforce.get_xmlbinary() does not exist"`

This is my postgrest.conf:
`db-uri = "postgres://authenticator:<OMITTED>"`
`db-schema = "salesforce"`
`db-anon-role = "anonymous"`
`jwt-secret = "<OMITTED>"`
`db-extra-search-path = "public"`

Setting the db-schema property to `db-schema = "public"` works fine and returns the expected result (a string), but this way I lose the possibility to access the salesforce schema.

This troubleshooting from Heroku didn't helped, as my search_path is as expected: https://help.heroku.com/OZ4RPNQS/how-do-i-resolve-function-get_xmlbinary-does-not-exist-errors-in-heroku-connect.

Any suggestion how to solve this issue? Thanks!

**Comment by steve-chavez** [comment]
Hey @Vizz85,

> but this way I lose the possibility to access the salesforce schema.

Hm, why is that? What error do you get?

The `search_path` should already include `salesforce`, but I guess you can be extra sure by doing:

```
db-extra-search-path = "salesforce, public"
```

**Comment by Vizz85** [comment]
Hi @steve-chavez , thank you for your reply.

In my constellation, the tables containing the rows which I need to update reside in the "salesforce" schema but all necessary functions are in the "public" schema, so setting `db-schema = "public"` and `db-extra-search-path = "salesforce, public"` does produce following error when e.g. trying a `PATCH /lead?id=eq.XXX` :

`{`
 `   "hint": null,`
`    "details": null,`
`    "code": "42P01",`
`    "message": "relation \"public.lead\" does not exist"`
`}`

This happens because only the `db-schema = "public"` receives an API endpoint.

It seems that when doing `db-schema = "salesforce"`, it won't look for that function `get_xmlbinary` anywhere else, but I think this is a common situation in postgres?

This is probably triggered by this trigger in the salesforce schema:
`                    BEGIN`
                    `  IF (get_xmlbinary() = 'base64') THEN  -- user op`
                    `    NEW._hc_lastop = 'PENDING';`
                   `     ...`

Next thing I would try is to manually update those triggers e.g. to `  IF (public.get_xmlbinary() = 'base64') THEN  -- user op` but I would prefer to not touch them, so I'm open to any suggestion.

Sincerely, Alessandro.

**Comment by Vizz85** [comment]
Hi @steve-chavez ,

wanted just to provide an update on my situation.

I managed to get a successful response while PATCHing a row adding following code to the Trigger Functions of my "salesforce" schema:

`SET search_path = 'public', 'salesforce', 'pg_catalog';`

<img width="1190" alt="Bildschirmfoto 2021-06-16 um 16 32 47" src="https://user-images.githubusercontent.com/13699434/122239279-1918d580-cec1-11eb-8483-832470562027.png">

So there seems to be an issue with the search_path not being correctly set by the request.
Although it works, I don't really like what I did, it is more like a hack.

Any idea if this is a configuration problem or a limitation of the application? My current conf is the same as in my first post.

Take care,
Alessandro

**Comment by steve-chavez** [comment]
Do you have access to [postgresql logs](https://postgrest.org/en/stable/admin.html#database-logs)?

> SET search_path = 'public', 'salesforce', 'pg_catalog';

postgrest should do this on every request: `SET search_path = 'salesforce', 'public';`(this is done precisely to prevent setting the search path on the function). This should show on the logs. 

> Although it works, I don't really like what I did, it is more like a hack.

Yeah, another way might be naming the schema explicitly in the code, like `public.get_xmlbinary() = 'base64'`.

**Comment by Vizz85** [comment]
Hi @steve-chavez ,

this is the log for a PATCH request when the SET search_path statement is not set in the function, no trace of the search path set by postgrest:
```
[DATABASE] [10-1]  sql_error_code = 42883 ERROR:  function get_xmlbinary() does not exist at character 9
[DATABASE] [10-2]  sql_error_code = 42883 HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
[DATABASE] [10-3]  sql_error_code = 42883 QUERY:  SELECT (get_xmlbinary() = 'base64')
[DATABASE] [10-4]  sql_error_code = 42883 CONTEXT:  PL/pgSQL function hc_lead_status() line 4 at IF
[DATABASE] [10-5]  sql_error_code = 42883 STATEMENT:
[DATABASE] [10-6] 	      WITH pg_source AS (UPDATE "salesforce"."lead" SET "middlename" = _."middlename" FROM (SELECT * FROM   json_populate_record (null:: "salesforce"."lead" , $1)) _  WHERE  "salesforce"."lead"."sfid" = 'xxxxx'::unknown  RETURNING "salesforce"."lead".*)
[DATABASE] [10-7] 	      SELECT '' AS total_result_set, pg_catalog.count(_postgrest_t) AS page_total, array[]::text[] AS header, coalesce(json_agg(_postgrest_t), '[]')::character varying AS body
[DATABASE] [10-8] 	      FROM (SELECT "pg_source".* FROM "pg_source"    ) _postgrest_t
```

Do you see anything unusual?

> Yeah, another way might be naming the schema explicitly in the code, like public.get_xmlbinary() = 'base64'

Yes, that was my first choice but it didn't worked for another function so I had to give up the plan.

**Comment by steve-chavez** [comment]
> Do you see anything unusual?

Hm, did you increase the logging verbosity - `log_statement = "all"`?

Also, what PostgREST version are using?

**Comment by Vizz85** [comment]
Hi @steve-chavez ,

this is the error with increased log verbosity:

```
[DATABASE] [16-1]  sql_error_code = 00000 LOG:  execute 1:
[DATABASE] [16-2] 	      WITH pg_source AS (UPDATE "salesforce"."lead" SET "middlename" = _."middlename" FROM (SELECT * FROM   json_populate_record (null:: "salesforce"."lead" , $1)) _  WHERE  "salesforce"."lead"."sfid" = '00Q5w00001tPSklEAG'::unknown  RETURNING "salesforce"."lead".*)
[DATABASE] [16-3] 	      SELECT '' AS total_result_set, pg_catalog.count(_postgrest_t) AS page_total, array[]::text[] AS header, coalesce(json_agg(_postgrest_t), '[]')::character varying AS body
[DATABASE] [16-4] 	      FROM (SELECT "pg_source".* FROM "pg_source"    ) _postgrest_t
[DATABASE] [16-5]  sql_error_code = 00000 DETAIL:  parameters: $1 = '{
[DATABASE] [16-6] 	    "middlename": "xxxxx"
[DATABASE] [16-7] 	}'
[DATABASE] [17-1]  sql_error_code = 42883 ERROR:  function get_xmlbinary() does not exist at character 9
[DATABASE] [17-2]  sql_error_code = 42883 HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
[DATABASE] [17-3]  sql_error_code = 42883 QUERY:  SELECT (get_xmlbinary() = 'base64')
[DATABASE] [17-4]  sql_error_code = 42883 CONTEXT:  PL/pgSQL function hc_lead_status() line 4 at IF
[DATABASE] [17-5]  sql_error_code = 42883 STATEMENT:
[DATABASE] [17-6] 	      WITH pg_source AS (UPDATE "salesforce"."lead" SET "middlename" = _."middlename" FROM (SELECT * FROM   json_populate_record (null:: "salesforce"."lead" , $1)) _  WHERE  "salesforce"."lead"."sfid" = 'xxxxx'::unknown  RETURNING "salesforce"."lead".*)
[DATABASE] [17-7] 	      SELECT '' AS total_result_set, pg_catalog.count(_postgrest_t) AS page_total, array[]::text[] AS header, coalesce(json_agg(_postgrest_t), '[]')::character varying AS body
[DATABASE] [17-8] 	      FROM (SELECT "pg_source".* FROM "pg_source"    ) _postgrest_t
```
From the deployment to Heroku log I see a **postgrest-0.5.0.0** which is the version mentioned in the README.md:
```
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Building on the Heroku-20 stack
remote: -----> Using buildpack: https://github.com/PostgREST/postgrest-heroku
remote: -----> PostgREST app detected
remote: -----> Exporting config vars
remote:        ANONYMOUS_URL
remote:        AUTHENTICATOR_URL
remote:        READ_WRITE_USER_URL
remote: -----> Restoring cached libraries
remote: -----> Restoring cached postgrest-0.5.0.0
remote: -----> Copying the config file builder
remote: -----> Creating Procfile
remote: -----> Persisting settings
remote: -----> ❤ stay declarative ❤
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote: 
remote: -----> Compressing...
remote:        Done: 10.1M
remote: -----> Launching...
remote:        Released v20
```
This probably refers specifically to the PostgREST Heroku package so I assume it is the last version when not differently set, right? Anyway I don't actively set the version number.

EDIT:
I saw that v0.5.0.0 is a pretty old version of postgrest.
So I tried to set in my app a config var `POSTGREST_VER` to `7.0.1` but it seems the last version is not linked in the postgrest-heroku buildpack:
```
-----> Building on the Heroku-20 stack
-----> Using buildpack: https://github.com/PostgREST/postgrest-heroku
-----> PostgREST app detected
-----> Exporting config vars
       ANONYMOUS_URL
       AUTHENTICATOR_URL
       POSTGREST_VER
       READ_WRITE_USER_URL
-----> Restoring cached libraries
-----> Could not find prebuilt postgrest-7.0.1
 !     Push rejected, failed to compile PostgREST app.
 !     Push failed
```

**Comment by steve-chavez** [comment]
> I saw that v0.5.0.0 is a pretty old version of postgrest.

Ah, yeah, really old. The `db-extra-search-path` config doesn't work there at all.

> So I tried to set in my app a config var POSTGREST_VER to 7.0.1

There's an open PR for upgrading the version: https://github.com/PostgREST/postgrest-heroku/pull/29. Could you help me with that :pray:? You could do another PR based off that one and make the corrections I suggested.

**Comment by Vizz85** [comment]
> Ah, yeah, really old. The db-extra-search-path config doesn't work there at all.

Oh ok, now everything makes sense.

> There's an open PR for upgrading the version: #29. Could you help me with that 🙏? You could do another PR based off that one and make the corrections I suggested.

I'll give it a try, it doesn't look too complicated

**Comment by Vizz85** [comment]
Hi @steve-chavez ,

can you please have a look at the new pull request #33 ?

In my test the latest version was successfully built:
![Bildschirmfoto 2021-06-17 um 22 45 35](https://user-images.githubusercontent.com/13699434/122469935-c8d36d80-cfbd-11eb-923f-4c0ede9c9aad.png)

And the `search_path` correctly set:
```
[DATABASE] [24-1]  sql_error_code = 00000 LOG:  statement: SET LOCAL search_path = 'salesforce', 'public';SET LOCAL "role" = 'read_write_user';SET LOCAL "request.jwt.claim.role" = 'read_write_user';SET LOCAL "request.method" = 'PATCH';SET LOCAL "request.path" = '/lead';SET LOCAL "request.header.host" = 'xxxxxx';SET LOCAL "request.header.connection" = 'close';SET LOCAL "request.header.prefer" = 'return=representation';SET LOCAL "request.header.authorization" = 'Bearer xxxxxxx';SET LOCAL "request.header.content-type" = 'application/json';SET LOCAL "request.header.user-agent" = 'PostmanRuntime/7.28.0';SET LOCAL "request.header.accept" = '*/*';SET LOCAL "request.header.cache-control" = 'no-cache';SET LOCAL "request.header.postman-token" =
[DATABASE] [24-2]  '5a5b3979-4fcb-4dd7-8cb1-b24e3fdcac2d';SET LOCAL "request.header.accept-encoding" = 'gzip, deflate, br';SET LOCAL "request.header.x-request-id" = '46bc50aa-cb72-410c-8b36-2fb5c973381f';SET LOCAL "request.header.x-forwarded-for" = '88.130.59.118';SET LOCAL "request.header.x-forwarded-proto" = 'https';SET LOCAL "request.header.x-forwarded-port" = '443';SET LOCAL "request.header.via" = '1.1 vegur';SET LOCAL "request.header.connect-time" = '1';SET LOCAL "request.header.x-request-start" = '1623962925405';SET LOCAL "request.header.total-route-time" = '0';SET LOCAL "request.header.content-length" = '35';
```

Thank you for your help!

Alessandro

**Comment by steve-chavez** [comment]
@Vizz85 Awesome! I've just merged your PR. Many thanks for jumping in to help :)

(Btw, I think on this version you don't even need to set `db-extra-search-path`, it should include `public` by default)

**Comment by Vizz85** [comment]
> (Btw, I think on this version you don't even need to set db-extra-search-path, it should include public by default)

@steve-chavez That's correct, forgot to mention it was no more necessary.

Indeed it worked like a charm with a very minimal configuration file and no extra Heroku config vars:
```
db-uri = "postgres://authenticator:xxxxxxx"
db-schema = "salesforce"
db-anon-role = "anonymous"
jwt-secret = "xxxxxxx"
```

Take care!
Alessandro
