### ISSUE TITLE
bin.begriffs.com is unavailable

### ISSUE THREAD

**Issue by supermario** [PostgREST/postgrest-heroku#8]
I'm getting the following trying to deploy:

```
remote: -----> Could not find prebuilt libraries
remote:
remote:  !     Push rejected, failed to compile DBAPI app
```

It appears that `bin.begriffs.com` DNS is down: 
- https://www.whatsmydns.net/#A/bin.begriffs.com
- https://www.whatsmydns.net/#CNAME/bin.begriffs.com

Would love to have the binaries back! 😊

**Comment by begriffs** [comment]
Thanks for reporting this. I'm updating my DNS information right now actually. I'll be sure to add the cname record to make this work. However it may take a day to propagate.

**Comment by begriffs** [comment]
@supermario try it again, the cname resolves for me now.

**Comment by supermario** [comment]
Domain is back, but appears files are still missing:

```
$ curl http://bin.begriffs.com/dbapi/heroku/ghc-libs.tar.xz
<html>
<head><title>404 Not Found</title></head>
<body>
<h1>404 Not Found</h1>
<ul>
<li>Code: NoSuchWebsiteConfiguration</li>
<li>Message: The specified bucket does not have a website configuration</li>
<li>BucketName: bin.begriffs.com</li>
<li>RequestId: 20B857D7F050C904</li>
<li>HostId: mu6D/7wu7ErOPuIbBesIKJdeylhyyo6vyDVD/EsI/qLHjveFfLP4vAal4rXoPKaFYiK4wC7GtPg=</li>
</ul>
<hr/>
</body>
</html>
```

**Comment by begriffs** [comment]
I adjusted the S3 settings, try again please.

**Comment by supermario** [comment]
Looks like we're back in business! 😄 

Thanks for your help, really excited to play around with Postgrest on Heroku 👍
